#-----------------------------------------------
# Required
#-----------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

#-----------------------------------------------
# Colorschemes
#-----------------------------------------------
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'sickill/vim-monokai'

[[plugins]]
repo = 'phanviet/vim-monokai-pro'

#-----------------------------------------------
# Plugins
#-----------------------------------------------
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  nnoremap <silent><C-t> :NERDTreeToggle<CR>
  nnoremap <silent><C-w> :NERDTree<CR>
'''

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  nmap <C-p> <Plug>AirlineSelectPrevTab
  nmap <C-n> <Plug>AirlineSelectNextTab
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
